import { build, context } from "esbuild";
import { execFileSync, spawn } from "child_process";
import { readFileSync, writeFileSync, readdirSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");
const srcDir = resolve(root, "src/sphinx_lumina_theme/_static_src");
const outDir = resolve(root, "src/sphinx_lumina_theme/theme/static");

const isWatch = process.argv.includes("--watch");

// Build JS bundle
async function buildJS() {
  const options = {
    entryPoints: [resolve(srcDir, "js/app.js")],
    bundle: true,
    outfile: resolve(outDir, "lumina.js"),
    format: "iife",
    minify: !isWatch,
    sourcemap: isWatch,
  };

  if (isWatch) {
    const ctx = await context(options);
    await ctx.watch();
    console.log("Watching JS...");
  } else {
    await build(options);
    console.log("JS built.");
  }
}

// Build CSS with Tailwind
function buildCSS() {
  const input = resolve(srcDir, "css/base.css");
  const output = resolve(outDir, "lumina.css");
  const tailwindBin = resolve(root, "node_modules/.bin/tailwindcss");

  if (isWatch) {
    spawn(tailwindBin, ["-i", input, "-o", output, "--watch"], {
      stdio: "inherit",
    });
    console.log("Watching CSS...");
  } else {
    execFileSync(tailwindBin, ["-i", input, "-o", output, "--minify"], {
      stdio: "inherit",
    });
    console.log("CSS built.");
  }
}

// Generate Python icon data from lucide-static SVGs
function buildIcons() {
  const iconsDir = resolve(root, "node_modules/lucide-static/icons");
  const outFile = resolve(root, "src/sphinx_lumina_theme/_icons.py");

  const files = readdirSync(iconsDir).filter((f) => f.endsWith(".svg"));
  const icons = {};

  for (const file of files) {
    const name = file.replace(".svg", "");
    const svg = readFileSync(resolve(iconsDir, file), "utf-8");
    // Extract inner content between <svg ...> and </svg>
    let inner = svg
      .replace(/<svg[^>]*>/, "")
      .replace(/<\/svg>/, "")
      .replace(/\n\s*/g, "")
      .trim();
    // Strip HTML comments iteratively to avoid partial remnants
    let prev;
    do {
      prev = inner;
      inner = inner.replace(/<!--[\s\S]*?-->/g, "");
    } while (inner !== prev);
    icons[name] = inner;
  }

  const entries = Object.entries(icons)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([name, inner]) => {
      // Escape backslashes first, then single quotes for Python string literals
      const escaped = inner.replace(/\\/g, "\\\\").replace(/'/g, "\\'");
      return `    "${name}": '${escaped}'`;
    })
    .join(",\n");

  const python = `"""Lucide icon SVG data — auto-generated by build-assets.js. Do not edit."""\n\nICONS = {\n${entries},\n}\n`;

  writeFileSync(outFile, python);
  console.log(`Icons built: ${files.length} icons.`);
}

buildIcons();
buildJS();
buildCSS();
